import React, { Component } from 'react'
import { Link } from 'react-router-dom'

class UseCases extends Component {
  render() {
    return (
      <div className="useCases">
        <h2 id="useCaseHeader">Suggested Use Cases</h2>

        <h3 className="h3useCase" id="subHeaderTone">
          Tone Analysis
        </h3>
        <p>
          The Tone Analyzer Service analyzes text at the document level and the sentence level. Use the document level
          analysis to get a sense of the overall tone of the document, and use the sentence level analysis to identify
          specific areas of your content where tones are the strongest.
        </p>
        <p>
          A tone whose score is less than 0.5 is omitted, indicating that the emotion is unlikely to be perceived in the
          content. A score greater than 0.75 indicates a high likelihood that the tone will be perceived.
        </p>
        <p>
          Detailed example by IBM found{' '}
          <Link className="userCase" to="http://customer-engagement-analytics.mybluemix.net/">
            here.
          </Link>
        </p>
        <h3 className="h3useCase">Predicting customer satisfaction in Twitter responses</h3>
        <p>
          Many companies are switching their customer support to Twitter. Twitter allows real-time answers, which helps
          to establish the brand as one with real people who care about their clients.
        </p>
        <p>
          The goal is to validate whether the tone of the conversations between the agent and the customer have any
          effect on overall customer satisfaction. Also identify the tone features that significantly impact customer
          satisfaction.
        </p>
        <h3 className="h3useCase">Predicting Twitter retweets and likes</h3>
        <p>
          Establishing a brand on Twitter is becoming a requirement for companies to succeed. An essential part of
          establishing you or your company is worth following is creating tweets that garner many likes and retweets.
        </p>

        <h3 className="h3useCase" id="subHeaderInsight">
          Personality Insights
        </h3>
        <p>
          The Personality Insights service lends itself to an almost limitless number of potential applications. By
          leveraging the Big Five personality characteristics, Needs, and Values, businesses and individuals alike can
          make more informed and more insightful decisions, and make more effective use of limited resources.
        </p>
        <p>
          Businesses can market to the most receptive target audience, they can acquire and retain more customers, and
          they can develop services that connect individuals and groups more effectively. Individuals can optimize how
          they market themselves to potential employers.
        </p>

        <h3 className="h3useCase">Targeted Marketing</h3>
        <p>
          Imagine an in-store retail experience that involves an interactive kiosk. Customers log in to the kiosk with a
          social media handle such as a Twitter ID. The kiosk quickly presents a set of personalized product and service
          offerings based on the customers' personality characteristics, needs, and values. The products and services
          include marketing campaigns, coupons, trial offers, and recommendations that are suited to each individual
          customer. The results match the right offerings to the most receptive customers, improving both the
          effectiveness of the offers and customer satisfaction.
        </p>

        <h3 className="h3useCase">Customer Aquisition</h3>
        <p>
          Personality portraits that are generated by the Personality Insights service can help businesses strengthen
          existing customer relationships and identify new customers. For example, people whose personalities evince a
          greater tendency for orderliness, self-discipline, and cautiousness and less immoderation are more likely than
          the random population to redeem coupons. Similarly, people's propensity to purchase specific kinds of products
          correlates with their personality characteristics. For example, shoppers whose personalities tend toward
          openness and conscientiousness are more likely to purchase organic milk, fruits, and vegetables.
        </p>

        <h3 className="h3useCase">Customer Care</h3>
        <p>
          Over the course of the customer engagement lifecycle, enterprises can use the Personality Insights service to
          build better, more lasting relationships with their customers. By better understanding customers and
          responding to them as individuals, businesses can
        </p>
        <ul className="bullet">
          <li>
            Use customers' personality characteristics to determine which interaction medium to use, what web page to
            display, and what video to share.
          </li>
          <br />
          <li>
            Present agents with information about a client who contacts the business. This information can let the agent
            give the client a more personalized experience by providing hints about how to talk to the client.
          </li>
          <br />
          <li>
            Consider a traveler who uses an online travel service to obtain recommendations for places to visit or dine.
            The travel service can examine the traveler's personality characteristics and suggest personalized
            site-seeing locations and restaurants that suit the traveler's personality. The service can go even further
            by working with local merchants to offer personalized coupons that match the traveler's interests.
          </li>
        </ul>

        <h3 className="h3useCase">Personal Connections</h3>
        <p>
          The Personality Insights service can match individuals and groups. Possible permutations can encourage
          individual-to-individual, individual-to-group, group-to-individual, and group-to-group connections by matching
          personality characteristics in the following domains:
        </p>
        <ul className="bullet">
          <li>Travel agent to traveler by offering suitable vacation packages to appropriate travelers.</li>
          <br />
          <li>Investment broker to investor by matching brokers to investors with whom they are likely to connect.</li>
          <br />
          <li>Personal dating via individual-to-individual matching.</li>
        </ul>
        <p id="ibmDetails">
          More details about IBM Watson's Personality Insights can be found{' '}
          <Link id="bluemix" className="userCase" to="https://console.bluemix.net/docs/services/personality-insights/">
            here.
          </Link>
        </p>
      </div>
    )
  }
}

export default UseCases
